services:
    prometheus:
        image: prom/prometheus:v3.5.0-rc.0
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./targets.json:/etc/prometheus/targets.json 
            - ./server.crt:/etc/prometheus/server.crt
