global:
    scrape_interval: 5s

scrape_configs:
    #  - job_name: 'node-exporter'
    #    static_configs:
    #      - targets: ['node-exporter:9100']
    - job_name: "nodes"
      file_sd_configs:
          - files:
                - /etc/prometheus/targets.json
    - job_name: "blackbox_health"
      metrics_path: /probe
      params:
          module: [http_2xx]
      static_configs:
          - targets:
                - http://192.168.56.101:32768
                - http://192.168.56.101:32679
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.56.101:9115
